name: 'Docker: Build and Push'

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-22.04
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7,linux/amd64,linux/arm64
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-qemu-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nevermined/contracts-spree:${{ github.sha }}
        platforms: linux/arm/v7,linux/amd64,linux/arm64
