name: Maven Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Pre-install
        run: |
          yarn
      - name: Generate Artifacts
        run: |
          yarn clean
          yarn compile

      - name: Generating Stubs
        run: |
#          curl -L https://get.web3j.io | sh
#          source ~/.web3j/source.sh
          curl -L https://github.com/web3j/web3j-cli/releases/download/v4.5.16/web3j-4.5.16.tar -o /tmp/web3j-cli.tar
          tar xvf /tmp/web3j-cli.tar -C /tmp/
          export PATH=$PATH:/tmp/web3j-4.5.16/bin
          scripts/maven.sh
          ls -R src/main/java/

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        env:
          GPG_TTY: $(tty)
        with:
          maven_goals_phases: "clean package deploy"
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
