name: Upgradability Tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Pre-install
        run: |
          yarn
          npx ganache-cli@~6.12.1 &
      - name: Compile and Lint
        run: |
          yarn lint
          yarn clean
          yarn compile
      - name: Run Upgrade Tests
        run: |
          yarn test:upgrade
          yarn deploy:development --deeper-clean
          git status
        env:
          NODE_OPTIONS: "--max-old-space-size=7500"
